# Generated by Django 4.2.2 on 2023-06-12 14:00

import ckeditor.fields
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to=products.models.upload_product_image)),
                ('logo', models.ImageField(upload_to=products.models.upload_company_logo)),
            ],
        ),
    ]
